version: '3'

services:
  service1:
    build: ./servico1
    ports:
      - "8001:8001"
  service2:
    build: ./servico2
    ports:
      - "8002:8002"
  gateway:
    build: ./gateway
    ports:
      - "8000:80"